### ISSUE TITLE
Audit and fix edx vs openedx workflows and templates

### ISSUE THREAD

**Issue by kdmccormick** [openedx/.github#2]
Based on a meeting of @nedbat , @feanil , and @carlosmuniz.

## Context

* This .github repo was copied from https://github.com/edx/.github
* We copied the repo instead of moving it because certain files *should* differ between the two orgs, such as the welcome page and security policy.
* Furthermore, we want a core set of `./workflow-templates` (e.g., "upgrade requirements") to be available in both organizations, which will require some amount of those templates to exist, duplicated, in each organization's .github repo.
* However, the _implementations_ of those shared workflows (in `./.github/workflows`) are currently duplicated between each organization and several repositories in each organization, which isn't great.

## Acceptance Criteria
* ~Ensure repos reference a shared workflow, not a copy.~ Done by @sarina .
* ~Ensure that openedx repos reference openedx workflows, not edx ones.~ Will be followed-up on in: https://github.com/openedx/.github/issues/32
* ~Ensure that this repo only has shared workflows related to Open edX.~ Done by @kdmccormick et al
* ~Ensure that the edx version of this repo only has edX-specific shared workflows.~ **Wontfix** -- it's up to edX to do that cleanup if they want to.
* ~Ensure that the openedx organization's .github repo contains all the `./workflow-templates` it needs~ Done by @kdmccormick et al
* ~Ensure that the edx organization's .github repo contains all the `./workflow-templates` it needs.~ **Wontfix** -- it's up to edX to do that cleanup if they want to.

**Comment by jmakowski1123** [comment]
Target H2

**Comment by sarina** [comment]
hey team! what's the relative importance of this? are there any particular steps more important than others? i think we can split this into smaller tickets, for sure. I understand why we want this but to me it seems of pretty low priority - perhaps opportunistic work as we encounter it. It does feel like a moving target.

**Comment by kdmccormick** [comment]
I'd say that relative importance of this individual issue is pretty low. It's confusing that we inconsistently use shared workflows from two different sources, but it's not going to break anyone's production. Supply-chain-wise it's not great that our org depends on code from the `edx` org, but it's just tooling code, so whatever.

That being said, I think the relative importance of regularly cleaning up some of the mess that surround us is pretty high. Kinda like: there's a pile of junk in the corner of our office, and cleaning it up is less important than our the project we're working on, but if we never clean up any of the junk in our office, then after a while we're going to have a disruptively messy workspace.

Could we make like a "low-priority quality-of-life" bucket for issues like this, which we could pull from every once in a while? https://github.com/openedx/tcril-engineering/issues/352 might also fall in that bucket.

**Comment by sarina** [comment]
@jmakowski1123 how would you want us to categorize this ticket (and its subsequent child tasks which I can make)? kyle suggests a "quality of life" epic or the like.

**Comment by kdmccormick** [comment]
@sarina is accomplishing a huge portion of this with her automated `openedx`->`edx` string replacement PRs in every openedx repository, so I'm assigning it to her and marking this as in progress. I can create a follow-up ticket for any of the AC that is left when her PRs are merged.

**Comment by sarina** [comment]
I've done some of this, but far from all.

> normalizing repos that currently use a copy of the shared workflow instead of reference to the shared workflow.

I could tell when a repo was using its own `upgrade-python-requirements` file because it called into `edx/testeng-ci`. I updated all these workflows to use the one defined in `.github/workflow_templates`.

It _seemed_ like all repos had the right version of commitlint; for those that had it I changed the references from edx/.github to openedx/.github

> If a shared workflow implementation is related to Open edX, then it should be defined in this repo only.
>If a shared workflow implementation is edX-specific, then it should be defined in edX's .github repo only.
>Before deleting the extraneous workflow implementations, all references to shared workflow implementations must be updated to point at the logical organization.

I haven't worked on any of this. I'm happy to help collaborate on this when we have time to tackle it, but I'm not doing more at the moment.

**Comment by kdmccormick** [comment]
@sarina @jmakowski1123 Good news, I re-reviewed after Sarina's cleanup and there's only one thing left to do:

> Ensure that openedx repos reference openedx workflows, not edx ones

I split that out into a follow-up issue which I think is a lot more manageable than this one originally was: https://github.com/openedx/.github/issues/32
