### ISSUE TITLE
Update workflow-templates to use latest actions versions

### ISSUE THREAD

**Issue by UsamaSadiq** [openedx/.github#31]
## Description
Update all the GitHub workflows templates present in the `workflow-templates` directory to use latest available actions versions:
- `checkout@v2` --> `checkout@v3`
- `setup-python@v2` --> `setup-python@v3`
- `setup-node@v2` --> `setup-node@v3`

**Comment by UsamaSadiq** [comment]
Added the issue to Arbi-bom's [GitHub project](https://github.com/orgs/edx/projects/12/views/1).

**Comment by iamsobanjaved** [comment]
This will be done by dependabot which we enabled in our owned repos.
